alertmanager:
  config:
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'sachinb9700@gmail.com'
      smtp_auth_username: 'sachinb9700@gmail.com'
<<<<<<< HEAD:kubernetes/monitoring/alertmanager-values.yaml
      smtp_auth_password: 'auth password'
=======
      smtp_auth_password: 'Email Password Here'
>>>>>>> 6a1a60b (security: stop tracking local Alertmanager SMTP credentials):kubernetes/monitoring/alertmanager-values.example.yaml

    route:
      receiver: email-notifications
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
      - name: "null"

      - name: email-notifications
        email_configs:
          - to: 'sachinb9700@gmail.com'
            send_resolved: true
