alertmanager:
  config:
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'sachinb9700@gmail.com'
      smtp_auth_username: 'sachinb9700@gmail.com'
      smtp_auth_password: 'auth password'

    route:
      receiver: email-notifications
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
      - name: email-notifications
        email_configs:
          - to: 'sachinb9700@gmail.com'
            send_resolved: true
