services:

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cloudcart_user
      POSTGRES_PASSWORD: cloudcart_password
      POSTGRES_DB: cloudcart
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudcart_user -d cloudcart"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - cloudcart-network

  auth-service:
    image: cloudcart-auth-service:python312-alpine
    container_name: auth-service
    env_file:
      - ./backend/auth-service/.env
    ports:
      - "8000:8000"
    depends_on:
     postgres:
      condition: service_healthy
    networks:
      - cloudcart-network

  frontend:
    image: cloudcart-frontend:multistage
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - auth-service
    networks:
      - cloudcart-network

volumes:
  postgres_data:

networks:
  cloudcart-network:
  