apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2026-07-02T19:30:00Z"
  generation: 329
  name: cloudcart
  namespace: argocd
  resourceVersion: "81897"
  uid: bdd93936-5c4b-4053-9304-71387745d5c2
spec:
  destination:
    namespace: cloudcart
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values/dev.yaml
    path: helm/cloudcart
    repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2026-07-03T20:50:47Z"
    status: Healthy
  history:
  - deployStartedAt: "2026-07-02T20:24:03Z"
    deployedAt: "2026-07-02T20:24:06Z"
    id: 6
    initiatedBy:
      username: admin
    revision: 38ef49aa74921fa1a29f1ad060f3464fcf238585
    source:
      path: helm/cloudcart
      repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
      targetRevision: main
  - deployStartedAt: "2026-07-02T20:32:35Z"
    deployedAt: "2026-07-02T20:32:38Z"
    id: 7
    initiatedBy:
      automated: true
    revision: b905e09ec874e6d89226ba5ac25bdfe7586a91ee
    source:
      path: helm/cloudcart
      repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
      targetRevision: main
  - deployStartedAt: "2026-07-02T20:36:10Z"
    deployedAt: "2026-07-02T20:36:14Z"
    id: 8
    initiatedBy:
      automated: true
    revision: e3aae1d88afea4a35eeb2f531ba58964f66c81d2
    source:
      path: helm/cloudcart
      repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
      targetRevision: main
  - deployStartedAt: "2026-07-03T19:48:40Z"
    deployedAt: "2026-07-03T19:48:46Z"
    id: 9
    initiatedBy:
      automated: true
    revision: 033ba107c376c542e0bdc1695fffbf3d7d06b799
    source:
      path: helm/cloudcart
      repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
      targetRevision: main
  - deployStartedAt: "2026-07-03T20:41:07Z"
    deployedAt: "2026-07-03T20:41:11Z"
    id: 10
    initiatedBy:
      automated: true
    revision: 02462396ef39ab5747eb77e8dd080122be3a7d84
    source:
      path: helm/cloudcart
      repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
      targetRevision: main
  - deployStartedAt: "2026-07-03T20:42:47Z"
    deployedAt: "2026-07-03T20:42:50Z"
    id: 11
    initiatedBy:
      username: admin
    revision: 02462396ef39ab5747eb77e8dd080122be3a7d84
    source:
      path: helm/cloudcart
      repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
      targetRevision: main
  - deployStartedAt: "2026-07-03T20:46:36Z"
    deployedAt: "2026-07-03T20:46:36Z"
    id: 12
    initiatedBy:
      username: admin
    revision: 02462396ef39ab5747eb77e8dd080122be3a7d84
    source:
      path: helm/cloudcart/values
      repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
      targetRevision: main
  - deployStartedAt: "2026-07-03T20:46:47Z"
    deployedAt: "2026-07-03T20:46:47Z"
    id: 13
    initiatedBy:
      username: admin
    revision: 02462396ef39ab5747eb77e8dd080122be3a7d84
    source:
      path: helm/cloudcart/values
      repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
      targetRevision: main
  - deployStartedAt: "2026-07-03T20:50:39Z"
    deployedAt: "2026-07-03T20:50:43Z"
    id: 14
    initiatedBy:
      automated: true
    revision: 02462396ef39ab5747eb77e8dd080122be3a7d84
    source:
      helm:
        valueFiles:
        - values/dev.yaml
      path: helm/cloudcart
      repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
      targetRevision: main
  - deployStartedAt: "2026-07-03T20:51:01Z"
    deployedAt: "2026-07-03T20:51:05Z"
    id: 15
    initiatedBy:
      username: admin
    revision: 02462396ef39ab5747eb77e8dd080122be3a7d84
    source:
      helm:
        valueFiles:
        - values/dev.yaml
      path: helm/cloudcart
      repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
      targetRevision: main
  operationState:
    finishedAt: "2026-07-03T20:51:05Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 02462396ef39ab5747eb77e8dd080122be3a7d84
        source:
          helm:
            valueFiles:
            - values/dev.yaml
          path: helm/cloudcart
          repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
          targetRevision: main
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2026-07-03T20:51:01Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Secret
        message: secret/postgres-secret configured
        name: postgres-secret
        namespace: cloudcart
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/auth-service-config unchanged
        name: auth-service-config
        namespace: cloudcart
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: PersistentVolumeClaim
        message: persistentvolumeclaim/postgres-pvc unchanged
        name: postgres-pvc
        namespace: cloudcart
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/frontend unchanged
        name: frontend
        namespace: cloudcart
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/postgres-service unchanged
        name: postgres-service
        namespace: cloudcart
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/auth-service unchanged
        name: auth-service
        namespace: cloudcart
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        images:
        - postgres:16
        kind: Deployment
        message: deployment.apps/postgres unchanged
        name: postgres
        namespace: cloudcart
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        images:
        - cloudcart-frontend:multistage
        kind: Deployment
        message: deployment.apps/frontend unchanged
        name: frontend
        namespace: cloudcart
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        images:
        - cloudcart-auth-service:v1
        kind: Deployment
        message: deployment.apps/auth-service unchanged
        name: auth-service
        namespace: cloudcart
        status: Synced
        syncPhase: Sync
        version: v1
      - group: autoscaling
        hookPhase: Running
        kind: HorizontalPodAutoscaler
        message: horizontalpodautoscaler.autoscaling/auth-service-hpa unchanged
        name: auth-service-hpa
        namespace: cloudcart
        status: Synced
        syncPhase: Sync
        version: v2
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/cloudcart-ingress unchanged
        name: cloudcart-ingress
        namespace: cloudcart
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 02462396ef39ab5747eb77e8dd080122be3a7d84
      source:
        helm:
          valueFiles:
          - values/dev.yaml
        path: helm/cloudcart
        repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
        targetRevision: main
  reconciledAt: "2026-07-03T21:02:26Z"
  resourceHealthSource: appTree
  resources:
  - kind: ConfigMap
    name: auth-service-config
    namespace: cloudcart
    status: Synced
    version: v1
  - kind: PersistentVolumeClaim
    name: postgres-pvc
    namespace: cloudcart
    status: Synced
    version: v1
  - kind: Secret
    name: postgres-secret
    namespace: cloudcart
    status: Synced
    version: v1
  - kind: Service
    name: auth-service
    namespace: cloudcart
    status: Synced
    version: v1
  - kind: Service
    name: frontend
    namespace: cloudcart
    status: Synced
    version: v1
  - kind: Service
    name: postgres-service
    namespace: cloudcart
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: auth-service
    namespace: cloudcart
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: frontend
    namespace: cloudcart
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: postgres
    namespace: cloudcart
    status: Synced
    version: v1
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    name: auth-service-hpa
    namespace: cloudcart
    status: Synced
    version: v2
  - group: networking.k8s.io
    kind: Ingress
    name: cloudcart-ingress
    namespace: cloudcart
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Helm
  summary:
    externalURLs:
    - http://cloudcart.local/
    - http://cloudcart.local/api(/|$)(.*)
    images:
    - cloudcart-auth-service:v1
    - cloudcart-frontend:multistage
    - postgres:16
  sync:
    comparedTo:
      destination:
        namespace: cloudcart
        server: https://kubernetes.default.svc
      source:
        helm:
          valueFiles:
          - values/dev.yaml
        path: helm/cloudcart
        repoURL: https://github.com/Sachinn-9700/CloudCart-Platform.git
        targetRevision: main
    revision: 4738e49eff5c770c0a15702956090f308e11e522
    status: Synced
