apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cloudcart
type: Opaque
stringData:
  POSTGRES_USER: cloudcart_user
  POSTGRES_PASSWORD: cloudcart_password
  POSTGRES_DB: cloudcart
  
