frontend:
  repository: sachinn9700/cloudcart-frontend
<<<<<<< HEAD
  tag: 34811e2

backend:
  repository: sachinn9700/cloudcart-auth-service
  tag: 34811e2
=======
  tag: initial
  replicas: 1

backend:
  repository: sachinn9700/cloudcart-auth-service
  tag: initial
  replicas: 1

>>>>>>> 8205ddc (fix(helm): add replica values and correct ConfigMap reference)

postgres:
  replicas: 1
  image: postgres:16
  DB_name: cloudcart

ingress:
  host: cloudcart.local

hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 50

