frontend:
  replicas: 1
  image: sachinn9700/cloudcart-frontend:initial

backend:
  replicas: 1
  image: sachinn9700/cloudcart-auth-service:initial

postgres:
  replicas: 1
  image: postgres:16
  DB_name: cloudcart

ingress:
  host: cloudcart.local

hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 50

