frontend:
  repository: sachinn9700/cloudcart-frontend
  tag: latest
  replicas: 2

authService:
  repository: sachinn9700/cloudcart-auth-service
  tag: latest
  replicas: 2

productService:
  repository: sachinn9700/cloudcart-product-service
  tag: latest
  replicas: 2

postgres:
  image: postgres:16
  replicas: 1
  DB_name: cloudcart

ingress:
  host: cloudcart.local

hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 60
