name: CloudCart CI

on:
  push:
    branches:
      - main

jobs:
  docker-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Build Information
        run: |
          echo "===== CloudCart CI ====="
          echo "Repository : ${{ github.repository }}"
          echo "Branch     : ${{ github.ref_name }}"
          echo "Commit     : ${{ github.sha }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify Login
        run: |
          echo "Docker Hub Login Successful"

      - name: Pipeline Completed
        run: |
          echo "Stage 2 Completed"